# Generated by Django 6.0.1 on 2026-01-10 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='addmission_number',
            new_name='admission_number',
        ),
    ]
