# Generated by Django 6.0.1 on 2026-01-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='hiHkFFgMOp0Avn7CXH1quRbS2XPiz3zO', editable=False, max_length=32, unique=True),
        ),
    ]
