# Generated by Django 6.0.1 on 2026-01-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0002_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='tKj2f0lgQfYoVyK2AGJikI6Lw3c4uvca', editable=False, max_length=32, unique=True),
        ),
    ]
