# Generated by Django 6.0.1 on 2026-01-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0003_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='sUw0itp0BFpg3GkA6364RdmbphV4Nqzx', editable=False, max_length=32, unique=True),
        ),
    ]
